### ISSUE TITLE
Wheel does not support Python3

### ISSUE THREAD

**Issue by Surgo** [michaeljohnbarr/django-timezone-utils#14]
https://pypi.org/project/django-timezone-utils/0.12/#files

@michaeljohnbarr May I setup [push on deploy by travis](https://docs.travis-ci.com/user/deployment/pypi/)?

If its OK, please add [Surgo](https://pypi.org/user/Surgo/) to [collaborators](https://pypi.org/manage/project/django-timezone-utils/collaboration/).

**Comment by pjdelport** [comment]
I just ran into this too. It looks like no source package got uploaded?

**Comment by michaeljohnbarr** [comment]
Alright. I'll get on this here in a little bit. My fault. Packaging is apparently not my forte. :(

**Comment by michaeljohnbarr** [comment]
@Surgo - I'm definitely happy to accept a pull request for that process, certainly! In the meantime, assuming I haven't somehow botched it again, I removed 0.12 since it was broken for Python 3. From what I can tell, once you release something broken on PyPi, there's no going back. Release 0.13 should fix this issue, and it should be available. I've also added you as a maintainer on PyPi.

I'll wait to close this until I get confirmation that Python 3 is working for 0.13. 😞

**Comment by pjdelport** [comment]
For future reference, uploading a source package (and/or Python 3 wheel package) to the 0.12 release would also have fixed this, without removing the release. The release wasn't broken, as such, just missing some files. :)

**Comment by michaeljohnbarr** [comment]
@Surgo / @pjdelport Are we good to close this, despite my misunderstanding and invalid version bump to 0.13?

**Comment by pjdelport** [comment]
@michaeljohnbarr: Yup, 0.13 works!

(It's probably still a good idea to upload a source distribution in addition to the wheels, though?)

**Comment by Surgo** [comment]
@michaeljohnbarr 0.13 works! Thank you :)

(After #15 merged, that push source and wheel to pypi)

**Comment by michaeljohnbarr** [comment]
Closed from https://github.com/michaeljohnbarr/django-timezone-utils/pull/15, which automates & should resolve this issue in the future.
